version: '3.9'

services:

  mariadb:
    build:
      context: .
      dockerfile: ./srcs/requirements/mariadb/Dockerfile
    networks:
      inception_network:
        aliases:
          - db
    env_file:
      - .env
    volumes:
      - ./data/db_data:/var/lib/mysql
    restart: unless-stopped

  wordpress:
    build:
      context: .
      dockerfile: ./srcs/requirements/wordpress/Dockerfile
    depends_on:
      - mariadb
    networks:
      inception_network:
        aliases:
          - wp
    env_file:
      - .env
    volumes:
      - ./data/wp_data:/var/www/html
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: ./srcs/requirements/nginx/Dockerfile
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      inception_network:
        aliases:
          - nginx
    env_file:
      - .env
    volumes:
      - ${CERTS_SSL}:/etc/nginx/certs/
      - ./srcs/requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./data/wp_data:/usr/share/nginx/html
    restart: unless-stopped

networks:
  inception_network:
