version: '3.9'

services:
  nginx:
    build:
      context: .
      dockerfile: ./srcs/requirements/nginx/Dockerfile
    ports:
      - "443:443"
    networks:
      my_network:
        aliases:
          - nginx
    volumes:
      - ${CERTS_SSL}:/etc/nginx/certs/
      - ./srcs/requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    env_file:
      - .env

networks:
  my_network: #bridge
